---
baseURL: "https://troubleshoot.sh"
languageCode: "en-us"
title: "Troubleshoot.sh"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation for the kubectl troubleshoot plugin"
googleAnalytics: ""

# Algoloia search
algolia:
  index: "prod_troubleshoot"
  appID: "NHTIKUBZ4C"

# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

staticDir:
    - ./static

Params:
  author: "Replicated, Inc."
  copyright: "Replicated, Inc"
  homepage_intro: "Troubleshoot is a set of kubectl plugins to run preflight checks or collect and analyze support bundles for any Kubernetes application"

  # matomo:
  #   host: "localhost:4000"
  #   site: "2"

  favicon: ""
  logo:
    preflight: "/images/preflight.svg"
    support_bundle: "/images/support.svg"
  pagetitle: "Troubleshoot.sh"
  permalink: "#"
  mainSections:
    - preflight
    - support-bundle
    - reference
menu:
  main:
    - Name: "Preflight"
      Weight: 1
      URL: "/preflight/overview"
    - Name: "Support Bundle"
      Weight: 2
      URL: "/support-bundle/overview"
    - Name: "Reference"
      Weight: 3
      URL: "/reference/overview"
---
